name: Bug Report
description: Create a report to help us improve
title: "Bug: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: Please fill this form to report the bug you encoutered on Puter
  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Type a description of what the bug does
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Type how we may reproduce the bug
      placeholder: Open the menu, click that button...
    validations:
      required: false
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: Tell us what you would expect to happen if the bug wasn't there
      placeholder: Its supposed to...
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: Addition Information or Screenshots (if applicable)
      description: You can add any additional informations, such as screenshots of the bug
      placeholder: You can add a screenshot by clicking the image icon in the text zone
    validations:
      required: false
  - type: checkboxes
    id: deployment
    attributes:
      label: Deployment
      description: Select on which deployment(s) you encountered the bug
      options:
        - label: Production (puter.com)
        - label: Development (`npm run start`)
        - label: Docker (via `docker run`)
        - label: Docker (via `docker-compose`)
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Puter version (if accessible)
      description: Type the version of Puter you were using when you encountered the bug
      placeholder: Click the profile button on the top-right, then "Settings". The version number will be printed at the bottom
    validations:
      required: false
